name: hello-world
on: 
  push:
    branches:
      - "master"
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: after push code to master, print "hello world"
        run: echo "hello world"
  run-project:
    runs-on: ubuntu-latest
    steps:
      - name: after push code to master, run run-project
        run: dotnet run