name: hello-world
on: 
  push:
    branches:
      - "master"
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: after push code to master, print "hello world"
        run: echo "hello world"
  
  
  run-project:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: after push code to master, run project
        run: |
              cd BulkyBook
              dotnet run
